CREATE TABLE Comics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(255) NOT NULL,
    isbn13 VARCHAR(255) NOT NULL,
    pDate VARCHAR(255) NOT NULL,
    seID INTEGER NOT NULL,
    pageID INTEGER NOT NULL,
    gID INTEGER NOT NULL,
    coID INTEGER NOT NULL
);

CREATE TABLE Genre (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    genre VARCHAR(255) NOT NULL
);

CREATE TABLE People (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    rID INTEGER NOT NULL,
    seID INTEGER NOT NULL
);

CREATE TABLE Roles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    role_name VARCHAR(255) NOT NULL
);

CREATE TABLE Characters (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    seID INTEGER NOT NULL
);

CREATE TABLE Series (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    series VARCHAR(255) NOT NULL
)

CREATE TABLE Publisher (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    company VARCHAR(255) NOT NULL
);

CREATE TABLE Pages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pCount INTEGER NOT NULL
);